### ISSUE TITLE
Preview images not showing up in web interface.

### ISSUE THREAD

**Issue by zircher** [jexom/sd-webui-depth-lib#20]
The preview images for the hand and shapes are not loading from the right path.  I tested this in Brave and Firefox.
https://tangent-zero.com/files/depth_library_error.png  [screen shot]
Right clicking on one of the links and I can get the URL/path as, http://127.0.0.1:7860/file=1_back.png .

The SD console returns...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 331, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'F:\\stable-diffusion-webui\\1_back.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 334, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path F:\stable-diffusion-webui\1_back.png does not exist.

**Environment**
- Running Python 3.10.8, Win10 (64 bit)
- Possible related note:  __file__ is not getting set by default.  I was able to fix that by using 'import inspect' and including
  __file__ = os.path.abspath(inspect.getsourcefile(lambda:0)) 
  at the beginning of the main.py script.

**To Reproduce**
1. This happens every time on launch of SD/A1111.

**Expected behavior**
Is for the preview images to populate properly.

**Comment by zircher** [comment]
In the possible related issue note, that value is __file__ (two leading and trailing underscores), this default variable should be set automatically, but it wasn't.

**Comment by zircher** [comment]
I installed newest versions of python and SD and this issues has stopped.
