### ISSUE TITLE
can't start extansion after install

### ISSUE THREAD

**Issue by oleg7zosimov** [jexom/sd-webui-depth-lib#32]
Hi there, trying to use this extansion, install them but when i try to start SD, they are crash with this, WBU start but doens't work, trying to fix and find the problem but can't please help me) 

Model loaded in 5.4s (load weights from disk: 0.6s, create model: 1.4s, apply weights to model: 0.9s, apply half(): 1.2s, move model to device: 1.1s).
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\gradio\routes.py", line 271, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "D:\stable-diffusion-webui-master (1)\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 504, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'dataset'

**Comment by NathanSamurai** [comment]
Have the same problem.

**Comment by Vsevolod-Shustov** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11855

**Comment by oleg7zosimov** [comment]
> [AUTOMATIC1111/stable-diffusion-webui#11855](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11855)

don't understand what i need to do in this case, please help)

**Comment by oleg7zosimov** [comment]
i want to use extansion depth lib )

**Comment by panjava001** [comment]
try gradio==3.32.0  and gradio_client==0.2.7 .   I had the same problem as you when installing 'gradio_client==0.2.10'

**Comment by oleg7zosimov** [comment]
> try gradio==3.32.0 and gradio_client==0.2.7 . I had the same problem as you when installing 'gradio_client==0.2.10'

just do that,  result is the same, doesn't work

ERROR:    Exception in ASGI application
etc
KeyError: 'dataset'

**Comment by PaperOrb** [comment]
I think I'll just wait for this extension to be updated then.

**Comment by scooller** [comment]
I have the same error un Vlad Automatic 
KeyError: 'dataset'

**Comment by BEL9ILLI** [comment]
1. Install Extensions - https://github.com/richrobber2/canvas-zoom
2. Download https://github.com/daswer123/canvas-zoom (Code-Download ZIP)
3. Unzip to SD canvas-zoom extensions folder (in my case (C:\stable-diffusion-portable-main\extensions\canvas-zoom))
4. You are awesome
5. Fixed bug with «Depth lib» and «Posex»

**Comment by SixBlueGod** [comment]
> > try gradio==3.32.0 and gradio_client==0.2.7 . I had the same problem as you when installing 'gradio_client==0.2.10'
> 
> just do that, result is the same, doesn't work
> 
> ERROR: Exception in ASGI application etc KeyError: 'dataset'

me too, it doesn't work.

**Comment by ghj1976** [comment]
me too

**Comment by Masayoshi-Ito-007** [comment]
me too, it doesn't work.

**Comment by numbereleven-a** [comment]
> 1. Install Extensions - https://github.com/richrobber2/canvas-zoom
> 
>     2. Download https://github.com/daswer123/canvas-zoom (Code-Download ZIP)
> 
>     3. Unzip to SD canvas-zoom extensions folder (in my case (C:\stable-diffusion-portable-main\extensions\canvas-zoom))
> 
>     4. You are awesome
> 
>     5. Fixed bug with «Depth lib» and «Posex»

Help me too but after that, canvas zoom itself stops working, if canvas zoom is reinstalled after that, an error will depth-lib  appear again

**Comment by jtydhr88** [comment]
see https://github.com/jexom/sd-webui-depth-lib/issues/36

**Comment by numbereleven-a** [comment]
> see #36

thanks! work now
