### ISSUE TITLE
Error executing callback ui_tabs_callback

### ISSUE THREAD

**Issue by numbereleven-a** [jexom/sd-webui-depth-lib#42]
I used the add-on for 2 months, today the controlnet was updated from 312 to 313 versions and the reactor and an error appeared, access to the tmp folder was and is.

*** Error executing callback ui_tabs_callback for G:\stable-diffusion\extensions\sd-webui-depth-lib\scripts\main.py
    Traceback (most recent call last):
      File "G:\stable-diffusion\modules\script_callbacks.py", line 153, in ui_tabs_callback
        res += c.callback() or []
      File "G:\stable-diffusion\extensions\sd-webui-depth-lib\scripts\main.py", line 47, in on_ui_tabs
        dataset = gr.Examples(examples=os.path.join(maps_path, t), inputs=[png_input_area],examples_per_page=24,label="Depth Maps", elem_id="examples")
      File "g:\stable-diffusion\venv\lib\site-packages\gradio\helpers.py", line 54, in create_examples
        examples_obj = Examples(
      File "g:\stable-diffusion\venv\lib\site-packages\gradio\helpers.py", line 201, in __init__
        self.processed_examples = [
      File "g:\stable-diffusion\venv\lib\site-packages\gradio\helpers.py", line 202, in <listcomp>
        [
      File "g:\stable-diffusion\venv\lib\site-packages\gradio\helpers.py", line 203, in <listcomp>
        component.postprocess(sample)
      File "g:\stable-diffusion\venv\lib\site-packages\gradio\components.py", line 1866, in postprocess
        return client_utils.encode_url_or_file_to_base64(y)
      File "g:\stable-diffusion\venv\lib\site-packages\gradio_client\utils.py", line 361, in encode_url_or_file_to_base64
        return encode_file_to_base64(path)
      File "g:\stable-diffusion\venv\lib\site-packages\gradio_client\utils.py", line 335, in encode_file_to_base64
        with open(f, "rb") as file:
    PermissionError: [Errno 13] Permission denied: 'tmp'

**Comment by wywywywy** [comment]
Try my fork it might work for you. https://github.com/wywywywy/sd-webui-depth-lib

**Comment by mikheys** [comment]
> I used the add-on for 2 months, today the controlnet was updated from 312 to 313 versions and the reactor and an error appeared, access to the tmp folder was and is.
> 
> *** Error executing callback ui_tabs_callback for G:\stable-diffusion\extensions\sd-webui-depth-lib\scripts\main.py Traceback (most recent call last): File "G:\stable-diffusion\modules\script_callbacks.py", line 153, in ui_tabs_callback res += c.callback() or [] File "G:\stable-diffusion\extensions\sd-webui-depth-lib\scripts\main.py", line 47, in on_ui_tabs dataset = gr.Examples(examples=os.path.join(maps_path, t), inputs=[png_input_area],examples_per_page=24,label="Depth Maps", elem_id="examples") File "g:\stable-diffusion\venv\lib\site-packages\gradio\helpers.py", line 54, in create_examples examples_obj = Examples( File "g:\stable-diffusion\venv\lib\site-packages\gradio\helpers.py", line 201, in **init** self.processed_examples = [ File "g:\stable-diffusion\venv\lib\site-packages\gradio\helpers.py", line 202, in [ File "g:\stable-diffusion\venv\lib\site-packages\gradio\helpers.py", line 203, in component.postprocess(sample) File "g:\stable-diffusion\venv\lib\site-packages\gradio\components.py", line 1866, in postprocess return client_utils.encode_url_or_file_to_base64(y) File "g:\stable-diffusion\venv\lib\site-packages\gradio_client\utils.py", line 361, in encode_url_or_file_to_base64 return encode_file_to_base64(path) File "g:\stable-diffusion\venv\lib\site-packages\gradio_client\utils.py", line 335, in encode_file_to_base64 with open(f, "rb") as file: PermissionError: [Errno 13] Permission denied: 'tmp'

I have the same error in both the original extension and the fork. Have you solved this error?
