### ISSUE TITLE
Depth Library tab doesn't show

### ISSUE THREAD

**Issue by Tiger102102** [jexom/sd-webui-depth-lib#45]
options I tried
checked for update
reistalled it from the link
restarted Webui
deleted the folder from extensions an reinstalled it 
disabled all other extensions 

nothing seems to work

Python 3.10

**Comment by benlau** [comment]
Did you found any error log in the output? I have similar problem and I found that a package is not installed. 

```
*** Error loading script: main.py
    Traceback (most recent call last):
      File "/Users/benlau/Development/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/benlau/Development/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/benlau/Development/stable-diffusion-webui/extensions/sd-webui-depth-lib/scripts/main.py", line 10, in <module>
        from basicsr.utils.download_util import load_file_from_url
    ModuleNotFoundError: No module named 'basicsr'
```

**Comment by jaylenchen** [comment]
I think I found the reason why the tab doesn't show. 
script "main.py" has this line : `from basicsr.utils.download_util import load_file_from_url`,but never used. delete it and restart ui can resolve it 
<img width="1493" alt="截屏2024-04-25 17 24 44" src="https://github.com/jexom/sd-webui-depth-lib/assets/72691225/4cea815a-402e-462e-bfda-be3e6f5fdb3d">

**Comment by brikston311** [comment]
Thanks Jaylenchan, that was the solution I needed to get it working after trying all the other steps Tiger had tried as well
